### ISSUE TITLE
Fairy Tales 2 - Outdated slabs

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#1028]
The bridges on Fairy Tales 2 use outdated wooden slabs. They are the ones from back when you had to destroy them with a pickaxe. An axe doesnt work.

![](http://i.imgur.com/x8SQXho.png)

![](http://i.imgur.com/mXLFJ0i.png)

**Comment by ghost** [comment]
@EyQu Please re-think that, keeping the old slabs is breaking textures
<a href="http://imgur.com/YHKcKjU"><img src="http://i.imgur.com/YHKcKjU.jpg" title="source: imgur.com" /></a>

**Comment by Pugzy** [comment]
I also thought about fixing this issue and I found two ways which would somewhat work.
- Make the old slabs new slabs (no longer fast breaking with pickaxe).
- Add a blockdrops filter turning old stone (wood slabs) to that of the new slabs so that no block errors are seen.

The first fix could remove the nostalgia of the map and go against the function intended (no axe is provided in the spawn chests). The second fix would then give the player wooden half slabs which would also require an axe to break.
