### ISSUE TITLE
Regioning error on Infernal Shadow

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1506]
I was trying to get to the wool room but tried to cut around to a corner. Just placed a block, jumped, and got stuck until a green member killed me.

![](http://i.imgur.com/4xtmvKW.png)

**Comment by Cevans98** [comment]
I mentioned this a while back in an issue that got closed due to the rest of the issue being invalid:

 - I don't even see why these spawn regions exist? Very few maps have them and also theyshould just be ended at the exit of spawn, not a few blocks radius of the building.

As mentioned by Para, it's incredibly glitchy for attackers and almost always results in a death.

**Comment by chickolympics** [comment]
I'll work on this tomorrow.
