### ISSUE TITLE
Teleport bug in Placid Spring

### ISSUE THREAD

**Issue by AudreyDx** [OvercastNetwork/Issues#1621]
It only happened once. When I was going to put the wool, i was teloported to the spawn, and I didn't touch the water. You can see that in the minute 05:45 https://youtube.com/watch?v=vmhW3zYi0NE

**Comment by matic0basle** [comment]
I don't think this is a map bug as the regions are fine.

It could be something to do with where you are on your screen and where you are on the servers. I had this issue because of NCP (not wool but positions) when it thought I was glitching. The plugin stopped me from going further because it thought I was glitching but on my screen I was at a different area.

Other than that I don't know what it could be but the regions are fine AFAIK unless they were being changed.

**Comment by lordcreeper01** [comment]
@matic0basle Regions were messed up

**Comment by matic0basle** [comment]
@lordcreeper01 They were fine before. Weird.
