### ISSUE TITLE
The Spawn can be blocked on Golden drought 3

### ISSUE THREAD

**Issue by Abusa3** [OvercastNetwork/Issues#1662]
This has happened a few times : 
![2015-02-27_21 40 18](https://cloud.githubusercontent.com/assets/9485005/6419946/69464582-beca-11e4-96bd-0d1536df5ad4.png)
![2015-02-27_21 40 04](https://cloud.githubusercontent.com/assets/9485005/6419947/694988c8-beca-11e4-891c-e3a1feb6c9ab.png)

**Comment by Ipskie** [comment]
Isn't it like this on GD as well? you can only block off that last block of the tube which IMO isn't that gamebreaking especially given 2 exits

**Comment by Abusa3** [comment]
i don't know about Golden drought (haven't played it in a while) , but here in Golden drought 3 if someone blocks the tube with wood it takes some time to break down , which can slow defenders quite a bit.

**Comment by rmsy** [comment]
This is because that last row (which is destructible, btw) is part of the island:
![Photo 1](https://cloud.githubusercontent.com/assets/406387/6429370/7ae9d7be-bf91-11e4-8db5-aff7b0980d9c.png)

There's no point in restricting players from doing this:
![Photo 2](https://cloud.githubusercontent.com/assets/406387/6429371/94274d2e-bf91-11e4-9108-496fdee416d2.png)

Because they'll just do this instead:
![Photo 3](https://cloud.githubusercontent.com/assets/406387/6429373/a87439ea-bf91-11e4-8caf-8a2143f20d0c.png)
