### ISSUE TITLE
Resident MapMakers Expires

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1666]
If you put the cursor over the badge it says that it expires in 14 days...

Example:

https://oc.tc/Supermon

**Comment by matic0basle** [comment]
Which is correct. They lose their rank after that time.

**Comment by Kitatist** [comment]
Huh?

So ure only resident for 15 days??

Last time they got a lot more time to test their maps...

**Comment by matic0basle** [comment]
It depends how they set it up with the staff. They can make it last longer if needed. Just up to what they decide on with staff but the rank does expire. Pretty sure default is 14 days and then they can make it longer.

The reason they had it longer before (not sure exactly) if because they asked staff for it. Pretty sure Elijah got it because it was a tournament map and there was a tournament that was being worked on.

**Comment by Kitatist** [comment]
:+1: Explanation
