### ISSUE TITLE
Fix minechat users not dying on rage maps with +1 lives

### ISSUE THREAD

**Issue by ryanw-se** [OvercastNetwork/Issues#1700]
The issue was reported a while ago, (6 months back) and it still persists. If a user joins a map such as plus side on the latest Minechat client they will spawn with no armor and a compass. They will not be able to die, and it basically stale mates the entire game. It only happens on maps with 1 or more lives.

Only maps on Rage that have more than one life, are affected by this issue.

**Comment by mrapple** [comment]
Where was it originally reported? What is this client?

**Comment by rywarsaw** [comment]
@mrapple It was originally reported to a moderator in game. I had been playing rage with friends and discovered the bug. We we're under the notion it had been fixed, but it appears that it hasn't.

I am not aware I if this is only a Rage issue. When the user spawns on his/her team's spawn, the minechat user appears with no armor, exactly how a observer would. This part of the bug happens on all maps.

Mine chat basically mimics the Minecraft client and allows you to join the server, but only talk and use commands. So a minechat client can run /join which is what concurs the bug above.

There is no way to tell them apart, that I am aware of, the best solution would probably be to detect if they aren't moving and kick them out of the game.

I suspect the issue of the minechat client not dying, is a packet related issue and probably not something OCN can fix. That being said this issue is game breaking and needs to be addressed as it can be abused to cheat in game.

**Comment by rywarsaw** [comment]
There is a chance that this is fixable, due to the nature of this only being replicable on rage maps with more than one life.

**Comment by mrapple** [comment]
Gotcha

**Comment by Electroid** [comment]
If they can't play, we shouldn't let them /join at all.

**Comment by ryanw-se** [comment]
@Electroid There is no way to currently detect whether someone is joining with a minechat client vs. a regular one. Unfortunately its not that easy, so I think the old title should stay.

**Comment by Electroid** [comment]
Ah I though the client sent a plugin channel message, but I guess not. Either way, someone should retest is now with the new respawn logic.

**Comment by ryanw-se** [comment]
@Electroid That doesn't make any sense, this issue only occurs on RAGE with maps that have more than 1+ live. They won't die in the first place to reach the death screen your talking about. I'm pretty sure this issue is a packet issue and not any other issue. 

The context should really be added back into the title because this only occurs in maps on RAGE and only RAGE with 2 lives. If there is one life they will just die, if there are two lives then they will not die and they will never reach the death screen to begin with. 

This is probably best fixed by not allowing people to type commands unless they have moved.

**Comment by tonybruess** [comment]
Why did you close this?
