### ISSUE TITLE
Map Update - Masarin II v.1.1

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1979]
Download: https://drive.google.com/file/d/0B1wU2uMNyVWENVllRURfdk5Kdm8/view?usp=sharing

Changelog: Added more signs to make it easier to locate stuff. Added more paths around the monument and some new iron mines there as well. Added some tnt inside the big tree over the core to make removing it easier.

**Comment by Qixit** [comment]
I think you forgot to mention that you also changed the XML. I've actually reverted back to the original XML and added the things you wanted changed, due to how many errors that continued to pop up. Here is a tutorial made by Anthonny on XML 1.4.0 Basics: XML 1.4.0 Basics: https://oc.tc/forums/topics/553ab5e867d522cd66003a3a

**Comment by ghost** [comment]
@Qixit Oh ok. Thanks!

**Comment by Qixit** [comment]
That's alright! :smile:
