### ISSUE TITLE
Incorrect wool color on scoreboard

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2012]
Since the total update of the server to 1.8, Blue Wool color is wrong on scoreboard, being the same as Light Blue's one.

Before: http://gyazo.com/9a7b03cb6438599b5155361739a46ea3

Now: http://gyazo.com/fa886f355154ce0181aded3d28a42298

**Comment by sarge-m** [comment]
I don't think there's any problem with this, the developers made blue wool a full square filled with blue and light blue wool is blue border with nothing inside of it.

**Comment by 2000thehecf1** [comment]
@PlayinCODMC No, that's because blue wool was touched and light blue wasn't.

**Comment by sarge-m** [comment]
Maybe they wanted to change things up? But you'll have to wait for staff to answer this correctly.

**Comment by AnthonyTag** [comment]
Intended, dark blue is more difficult to read.

**Comment by jedediah** [comment]
I fixed it

**Comment by 2000thehecf1** [comment]
@jedediah Thanks!

**Comment by Pablete1234** [comment]
@jedediah this also applies to chat colors, 
![image](https://cloud.githubusercontent.com/assets/11789291/13026257/55d13384-d221-11e5-81be-927bfe1d44eb.png)

Also i belive a blue and a light blue flag would have the same issue, since on Nartica, no color is set for the flag (and the banner base is blue), but in the scoreboard it shows up as chatColor.blue, not as chatColor.dark_blue
OCN should "decide" what color equals what, and do it everywhere, atm it seems like blue dye = blue in chat, and light blue dye = blue, imo, either blue dye should be dark blue in chat, or light blue should be aqua in chat
