### ISSUE TITLE
The Fenland - Invisible players in an area

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2124]
While defending on the map, I noticed that sometimes, players become invisible when walking in an area of the map.

https://youtu.be/E_JLZelf7Ik

The effects looks be chunk-dependant, as if I'm walking a few blocks away, I am able to see me again in F5 mode, or version dependant, and I don't know if it is really fixable.

**Comment by Brottweiler** [comment]
Seems related to that thing where the chunk seems to be missing so you fall slowly and stuff.

**Comment by ghost** [comment]
Isn't fixed https://youtu.be/Rk5AfI63QR4

**Comment by AnthonyTag** [comment]
Is this an MC bug by any chance? Like a chunk issue? Cause idk how we could really fix a chunk issue. Maybe copy and paste the whole map to a new world? But that may cause even more chunk issues.

**Comment by ghost** [comment]
@AnthonyTag I think you can just regenerate that chunk

**Comment by Qixit** [comment]
@TiTo-418 Video is private. I'll look into this again, but the video could help.

**Comment by Qixit** [comment]
I already created new chunks on all\* versions of the Fenland (http://imgur.com/bUuRY3l).

**Comment by ghost** [comment]
@Qixit It's public again, sorry

**Comment by Qixit** [comment]
Thanks @TiTo-418 ! I reproduced the problem, however this issue is quite unique: The chunk say's its there in Mcedit, however it acts as if it isn't. The only way of fixing it was adding a block in the chunk, while in mcedit, so for the time being there's a single barrier block located past the max build height.
http://imgur.com/GGRRFJM
