### ISSUE TITLE
Bugged dead messages

### ISSUE THREAD

**Issue by Whiteverr** [OvercastNetwork/Issues#2182]
I was playing Spooky Smog and I picked up punch bow, and started to camping.

So I started shooting people off bridges, and the shot distance was just weird
![](http://i.imgur.com/saPOHVZ.png)

![](http://i.imgur.com/mFmoPIJ.png)

![](http://i.imgur.com/mseXZTo.png)

**Comment by Brottweiler** [comment]
> the shot distance was just weird

What do you mean? How is it weird?

**Comment by Whiteverr** [comment]
like that wasn't the real shot distance, I shot them just by 20 blocks or so
and it says +100 :S

**Comment by Pugzy** [comment]
If I recall correctly Smog has/had a really high floor level (not at y = 0). My guess is that this is the same on the Halloween version, I'll look into this.

Can confirm, the height of the  map is around 120 blocks, so people fall in the void 100 blocks then get killed by it, PGM classes this as 120 blocks fall then death.

**Comment by 96alexmr** [comment]
Just my two cents, but it should be showing where the bow actually hit the player, not were the died.

**Comment by Electroid** [comment]
This is a map issue.

**Comment by Pugzy** [comment]
@Electroid This is caused due to the height of the map however the plugin works out how far the player fell into the void, the wording within the death message could also be confused.

The from x blocks should be the distance of the bow shot that caused them to fall not the distance they fell. I feel the current message (like seen in the above screenshots) is pretty useless and a shorter `was shot into the void by` would be more applicable than a non-meaningful fall distance.

**Comment by Pugzy** [comment]
![](http://i.imgur.com/Z9PMsHI.png)

Ways to fix this;
- Remove the distance from the death message (when shot into the void).
- Re-word to show that the distance is how far they fell (not shot from).
- Calculate how many blocks they were shot in order for them to be knocked rather than blocks fallen.

@Electroid I still think this is plugin based, if not every map has this "issue" this case just an extreme.

**Comment by jedediah** [comment]
this is a bug, it's supposed to display the shot distance
