### ISSUE TITLE
Observers get stuck in a teleport loop after falling into the void

### ISSUE THREAD

**Issue by jedediah** [OvercastNetwork/Issues#2391]
Need a repro for this

**Comment by eudaldca** [comment]
Just jump to the void while in obs. It fails to teleport you server-side, but it teleports you client-side. Therefore, the server still thinks you're in the void and keeps on teleporting you to the spawn, and since spawns have a spawn radius, there you have it. @jedediah

**Comment by andreskv** [comment]
It used to get bugged only when dying with elytra, but now it seems to happen whenever you jump into the void.
https://youtu.be/ygZE1965rGA

**Comment by nigges60** [comment]
Happened multiple times.
https://youtu.be/hetEV9sF0MM

**Comment by JettGannaway** [comment]
I (think) I've worked out how to replicate this, or, at least, one way to do it. 
- Go into a team with `/join`
- Die by jumping into the void
- Do **not** respawn. Stay at death screen
- When the round has finished in such a way that all are put into `/obs`, you will be at the observer spawn platform, glitching around. 

Hope this can help clear the issue up, it can be a pain at time to deal with.

**Comment by Pablete1234** [comment]
@jedediah are you still unable to reproduce this?

**Comment by jedediah** [comment]
Fixed

**Comment by Pablete1234** [comment]
@jedediah Well, you don't end up in a teleport loop anymore, but you don't get teleported at all, you should get teleported to spawn obs, not only set the player to be flying

**Comment by Pablete1234** [comment]
@jedediah This doesn't work very good when using portals that teleport obs into the void (war wars uses that to prevent obs from leaving the area arround the map), since you just get teleported to -15000, and with the new method, your flight gets resetted, and the event is cancelled, but you can just keep flying and nothing will happen

Really, when a move or teleport event of an obs ends bellow 64, find a respawn position for spawn obs, and set the move/teleport event "setTo(the spawn point)"

**Comment by jedediah** [comment]
Do any maps do that besides war wars?

**Comment by Pablete1234** [comment]
@jedediah maps with death-void.xml lincluded could also apply

**Comment by AnthonyTag** [comment]
I made a fix that should make this new system work without problems with `void-death.xml`.
