### ISSUE TITLE
Not really sure about this(off hand intrusion with normal hand.)

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2411]
Basically when you are in the lobby this occured, I right clicked the gizmo 'grabber'(i guess you could call it that) and it automatically uses the off-hand function(in this case a bow). I think it should be overridden to only use the normal hand function, right?

http://imgur.com/LD2e8EP

**Comment by Brottweiler** [comment]
The lobby should not really have a bow there anyway, it's because the sign normally does nothing when rightclicking air, so it will use the left hand slot if there is something there you can right click with. Because it opens a server side GUI after that, the bow just stays pulled back.

I don't think this is an issue.
