### ISSUE TITLE
Map Update - Under The Sea 5x5

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2485]
Edited a few map bugs and increased  double jump power.

DL: https://www.dropbox.com/s/hdy8w13br18ubro/Under%20The%20Sea%205x5.zip?dl=0

**Comment by samthecat** [comment]
@GoldenOre Make sure you're updating the map version when you make an update.
Always follow the tabbing conventions for the XML. You can find a guide [here](https://oc.tc/forums/topics/5674a2ca5f35b90338000583). 
Also, your map image file should be a `.png` not `.jpg` like you have it now. The new image also does not have the correct dimensions for a `map.png` file `(290x246)`, because of this, I've just used the old image.

**Comment by GoldenOre** [comment]
Ahh my bad, it seems like I updated old xml instead of the latest.
