### ISSUE TITLE
Build : Parkour Yellow team scoring bug

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2556]
So, if you are familiar with the map and how it works, you should know that you may only score a point during the competing stage, and not the building/testing phase. There are 8 teams, and each color is identified by a number in the XML, player-1, player-2, player-3, etc. Yellow is identified as "player-8", and their arena as arena-8. The problem is, yellow team can score points at each "phase" of the map, even in the building stage, where they can instantly win a game by going through their end point portal 8 times to score 8 out of 8 points, thus ending the game. I looked at the XML of the map, and noticed something interesting, and I'm not sure if this was intended at all.
At line 2703, you can see that it will say `<!-- Check if team has already completed arena`, and following that it lists all the arenas EXCEPT for arena 8, which is the only arena missing. I think this may be the cause(s) of the problem, not completely sure though.

**Comment by mitchts** [comment]
Those filters only check if the arena has already been completed by that team during the racing phase of the map. As the yellow arena is the last arena, it doesn't need that filter as the player will be sent to the win room and end the game. Because of this, the yellow arena score box is filtered by the race phase only.  
I'm sure I fixed this a few days ago, and it doesn't look like the map has been played since then. When did you make these observations?

**Comment by jexeI** [comment]
I believe it was last week, so your change probably fixed it.

**Comment by mitchts** [comment]
Closing for now as I believe it has already been fixed. If this happens to occur again, please reopen the issue.
