### ISSUE TITLE
Cloud Nine doesn't have killrewards

### ISSUE THREAD

**Issue by amactus** [OvercastNetwork/Issues#2559]
String doesn't drop, meaning wool can't be made and therefore you can't win

**Comment by jexeI** [comment]
This is not the case anymore, weather it has been fixed or not. I've just tested it out with elephantLocator just today, and it worked. Also, string dropping is  `<itemremove>`, which is why they don't drop when you kill someone. That, however does not mean you won't get any string when you killed a person due to the `<killreward>`.
