### ISSUE TITLE
Map Update: Arodisae 

### ISSUE THREAD

**Issue by amactus** [OvercastNetwork/Issues#2629]
Last issue I made had a huge XML bug in it, making the map unplayable. This fixes it and makes a minor map change (updating spawnkit chest in obs spawn)

https://dl.dropboxusercontent.com/u/51144252/Arodisae.zip

**Comment by Pugzy** [comment]
That wasn't fun to update, you should be able to download the latest version from the map page.

Please try and follow the basic packaging instructions on `docs.oc.tc`, the map wasn't pruned and the `map.png` was nowhere near the correct dimensions.

A few XML changes that needed to be done.
- Bump the version number by 0.0.1 because it was an update.
- Add a `<slug>` element referencing the old map name (means it pulls ratings from it).
- Moving a few elements around (objectives after teams, spawns, kits).
- Changing the id `bluemon` to be the region not the objective.
- Adding the region as an attribute to the proximity alarm.

**Comment by amactus** [comment]
@iPGz apologies, as I said, the previous update was really broken, including the map so I couldn't use the download from the map page. it won't happen again
